services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volume/nginx/conf.d:/etc/nginx/conf.d
      - ./volume/nginx/html:/usr/share/nginx/html
